# Generated by Django 5.2 on 2025-04-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='deskripsi',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
